# Generated by Django 5.2 on 2025-09-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_user_created_at_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('rent_payment', 'Rent Payment'), ('deposit', 'Security Deposit'), ('maintenance', 'Maintenance Fee'), ('utility', 'Utility Bill')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('fee', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='Users.user')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='Users.user')),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['reference'], name='Transaction_referen_214741_idx'), models.Index(fields=['payer', 'status'], name='Transaction_payer_i_a0b285_idx'), models.Index(fields=['status', 'initiated_at'], name='Transaction_status_4117ee_idx')],
            },
        ),
    ]
