# Generated by Django 5.2 on 2026-04-26 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
        ('Users', '0011_user_account_name_user_account_number_user_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='Users.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='Users.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('rent_payment', 'Rent Payment'), ('deposit', 'Security Deposit'), ('maintenance', 'Maintenance Fee'), ('utility', 'Utility Bill'), ('subscription', 'Premium Subscription'), ('booking_fee', 'Booking Fee')], max_length=20),
        ),
    ]
