# Generated by Django 5.2 on 2026-04-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Properties', '0009_properties_listing_type_properties_max_nights_and_more'),
        ('Users', '0009_user_subscription_started_at_user_subscription_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nightly_rate', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_nights', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('caution_fee', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('amount_paid', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('airbnb', 'Airbnb'), ('booking_com', 'Booking.com'), ('other', 'Other')], default='direct', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('landlord_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to='Users.user')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Properties.properties')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'status'], name='Bookings_bo_propert_9c731f_idx'), models.Index(fields=['check_in_date', 'check_out_date'], name='Bookings_bo_check_i_8d1b7c_idx'), models.Index(fields=['booking_reference'], name='Bookings_bo_booking_d0d23d_idx')],
            },
        ),
    ]
