# Generated by Django 5.2 on 2026-05-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment', 'Payment Received/Sent'), ('invoice', 'New Invoice'), ('lease', 'Lease Update'), ('maintenance', 'Maintenance Update'), ('booking', 'Booking Update'), ('subscription', 'Subscription Update'), ('security', 'Security Alert'), ('system', 'System Alert')], default='system', max_length=20),
        ),
    ]
