# Generated by Django 5.2 on 2025-09-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Properties', '0004_rename_user_id_properties_landlord'),
        ('Users', '0002_user_created_at_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_months', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('current_period', models.IntegerField(default=1)),
                ('total_periods', models.IntegerField()),
                ('next_payment_date', models.DateField()),
                ('security_deposit', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('deposit_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('deducted', 'Deducted')], default='pending', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('days_overdue', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='Properties.properties')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='Users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentInitiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('proposed_rent_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('proposed_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('proposed_security_deposit', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_initiations', to='Users.user')),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_initiations', to='Properties.properties')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_initiations', to='Users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], max_length=20)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Rent.rent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='Users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
