# Generated by Django 5.2 on 2025-09-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rent', '0001_initial'),
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_payments', to='Transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['tenant', 'payment_status'], name='Rent_rent_tenant__2f3635_idx'),
        ),
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['rental_property', 'payment_status'], name='Rent_rent_rental__13df18_idx'),
        ),
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['start_date', 'end_date'], name='Rent_rent_start_d_18f854_idx'),
        ),
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['next_payment_date'], name='Rent_rent_next_pa_26eace_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinitiation',
            index=models.Index(fields=['rental_property', 'status'], name='Rent_rentin_rental__467705_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinitiation',
            index=models.Index(fields=['tenant', 'status'], name='Rent_rentin_tenant__12d567_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinitiation',
            index=models.Index(fields=['expires_at'], name='Rent_rentin_expires_a1d579_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['rent', 'payment_status'], name='Rent_rentpa_rent_id_8bd649_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['due_date', 'payment_status'], name='Rent_rentpa_due_dat_6c1515_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['payment_reference'], name='Rent_rentpa_payment_08dd8a_idx'),
        ),
    ]
