# Generated by Django 5.2 on 2026-04-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='Rent.rent')),
            ],
            options={
                'ordering': ['installment_number'],
                'indexes': [models.Index(fields=['rent', 'status'], name='Rent_paymen_rent_id_70b0f2_idx'), models.Index(fields=['due_date', 'status'], name='Rent_paymen_due_dat_e9a67c_idx')],
                'unique_together': {('rent', 'installment_number')},
            },
        ),
    ]
