# Generated by Django 5.2 on 2026-04-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0003_paymentschedule'),
        ('Users', '0009_user_subscription_started_at_user_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rent',
            name='tenant_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rentinitiation',
            name='tenant_name',
            field=models.CharField(default='mustapha', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentinitiation',
            name='tenant_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='Users.user'),
        ),
        migrations.AlterField(
            model_name='rentinitiation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_initiations', to='Users.user'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_payments', to='Users.user'),
        ),
    ]
