# Generated by Django 5.2 on 2026-05-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0002_invoice_monnify_contract_code_and_more'),
        ('Rent', '0004_rent_tenant_name_rent_tenant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='Invoices.invoice'),
        ),
        migrations.AddField(
            model_name='rent',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rentinitiation',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('custom', 'Custom')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentinitiation',
            name='proposed_rent_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually'), ('custom', 'Custom')], default='monthly', max_length=20),
        ),
    ]
