# Generated by Django 5.2 on 2026-05-15 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0005_paymentschedule_invoice_rent_tenant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rent',
            name='landlord_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='lease_document_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='lease_public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='tenant_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
