# Generated by Django 5.2 on 2026-05-15 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0006_rent_is_signed_rent_landlord_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='lease_public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
