# Generated by Django 5.2 on 2025-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_created_at_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
