# Generated by Django 5.2 on 2026-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_usertokenrevocation_alter_user_role_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('endpoint', models.CharField(max_length=100)),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('window_start', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['ip', 'endpoint'], name='Users_ratel_ip_62e6f6_idx')],
                'unique_together': {('ip', 'endpoint')},
            },
        ),
    ]
