# Generated by Django 5.2 on 2026-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monnify_subaccount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_step',
            field=models.CharField(choices=[('basic', 'Basic'), ('kyc', 'KYC Pending'), ('complete', 'Complete')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
