# Generated by Django 5.2 on 2026-05-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_user_account_name_user_account_number_user_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
