# Generated by Django 5.2 on 2026-05-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_user_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
    ]
