# Generated by Django 5.2 on 2026-05-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_remove_user_bvn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True),
        ),
    ]
