# Generated by Django 5.2 on 2026-06-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_user_last_login_notification_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_replies', to='Users.user')),
                ('support_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Users.supportmessage')),
            ],
        ),
    ]
