# Generated by Django 5.2 on 2026-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
        ('Users', '0018_add_support_message_reply'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'isactive'], name='Users_user_role_156032_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['isactive'], name='Users_user_isactiv_e56461_idx'),
        ),
    ]
