# Generated by Django 5.2 on 2026-04-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0001_initial'),
        ('Rent', '0003_paymentschedule'),
        ('Users', '0009_user_subscription_started_at_user_subscription_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('issued_to_name', models.CharField(max_length=150)),
                ('issued_to_email', models.EmailField(blank=True, max_length=254)),
                ('issued_to_phone', models.CharField(blank=True, max_length=20)),
                ('line_items', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=10)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Bookings.booking')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to='Users.user')),
                ('rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Rent.rent')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['issued_by', 'status'], name='Invoices_in_issued__8c1ea0_idx'), models.Index(fields=['due_date', 'status'], name='Invoices_in_due_dat_d3a54e_idx'), models.Index(fields=['invoice_number'], name='Invoices_in_invoice_8be9df_idx')],
            },
        ),
    ]
