# Generated by Django 5.2 on 2026-04-26 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
        ('Invoices', '0001_initial'),
        ('Rent', '0004_rent_tenant_name_rent_tenant_phone_and_more'),
        ('Users', '0011_user_account_name_user_account_number_user_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='monnify_contract_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='monnify_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='virtual_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['public_id'], name='Invoices_in_public__b38423_idx'),
        ),
    ]
