# Generated by Django 5.2 on 2025-09-12 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
        ('Properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.RemoveField(
            model_name='saved_properties',
            name='address_id',
        ),
        migrations.AddField(
            model_name='properties',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='properties',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='properties',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/main_images/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('studio', 'Studio'), ('commercial', 'Commercial')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='properties',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saved_properties',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Properties.properties'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.address'),
        ),
    ]
