# Generated by Django 5.2 on 2025-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_alter_properties_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='properties',
            name='yearly_rent',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
