# Generated by Django 5.2 on 2025-09-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0003_alter_properties_monthly_rent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='user_id',
            new_name='landlord',
        ),
    ]
