# Generated by Django 5.2 on 2025-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0004_rename_user_id_properties_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='properties',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('studio', 'Studio'), ('commercial', 'Commercial'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex'), ('other', 'Other')], default='apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='properties',
            name='yearly_rent',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
