# Generated by Django 5.2 on 2025-09-23 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0005_alter_properties_description_and_more'),
        ('Users', '0006_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saved_properties',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='saved_properties',
            unique_together={('user_id', 'property_id')},
        ),
    ]
