# Generated by Django 5.2 on 2025-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0006_properties_views_count_saved_properties_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under_maintenance', 'Under Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
