# Generated by Django 5.2 on 2025-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0007_properties_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='main_image',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
