# Generated by Django 5.2 on 2026-04-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0008_alter_properties_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='listing_type',
            field=models.CharField(choices=[('lease', 'Long-Term Lease'), ('short_term', 'Short-Term / Airbnb'), ('hybrid', 'Hybrid')], default='lease', max_length=20),
        ),
        migrations.AddField(
            model_name='properties',
            name='max_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='min_nights',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='nightly_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='yearly_rent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.CreateModel(
            name='PropertyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('prepaid_meter', 'Prepaid Meter'), ('smart_lock', 'Smart Lock'), ('wifi', 'WiFi'), ('gate_code', 'Gate Code'), ('generator', 'Generator'), ('water_pump', 'Water Pump'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='Properties.properties')),
            ],
            options={
                'ordering': ['asset_type', 'label'],
            },
        ),
    ]
