# Generated by Django 5.2 on 2026-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0009_properties_listing_type_properties_max_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
