# Generated by Django 5.2 on 2026-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
        ('Properties', '0010_add_property_flagging'),
        ('Users', '0018_add_support_message_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'properties'},
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['is_published', 'status'], name='Properties__is_publ_9f0ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['landlord', 'status'], name='Properties__landlor_2f43a1_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['listing_type'], name='Properties__listing_539395_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['property_type'], name='Properties__propert_a8cf40_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['is_featured'], name='Properties__is_feat_dc988a_idx'),
        ),
        migrations.AddIndex(
            model_name='properties',
            index=models.Index(fields=['-created_at'], name='Properties__created_e1dc11_idx'),
        ),
    ]
