# Generated by Django 5.2 on 2026-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0011_alter_properties_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyasset',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveField(
            model_name='propertyasset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='propertyasset',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='propertyasset',
            name='label',
        ),
        migrations.RemoveField(
            model_name='propertyasset',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='propertyasset',
            name='provider',
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='category',
            field=models.CharField(choices=[('appliance', 'Appliance'), ('furniture', 'Furniture'), ('fixture', 'Fixture'), ('utility', 'Utility/Access'), ('other', 'Other')], default='appliance', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
